import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#25292e",
  },
  header: {
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
  },
  headerTitle: {
    color: "yellow",
    fontSize: 30,
    fontWeight: "900",
  },
  listContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  habitRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1e2126",
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 10,
  },
  habitName: {
    color: "white",
    fontSize: 16,
    flex: 1,
    marginLeft: 12,
  },
  editButton: {
    padding: 6,
    marginLeft: 4,
  },
  text: {
    color: "white",
  },
  fab: {
    position: "absolute",
    right: 20,
    bottom: 30,
    width: 56,
    height: 56,
    borderRadius: 12,
    backgroundColor: "yellow",
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  modalCard: {
    backgroundColor: "#1e2126",
    borderRadius: 16,
    padding: 20,
  },
  modalTitle: {
    color: "yellow",
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 16,
    alignSelf: "center",
  },
  modalInput: {
    backgroundColor: "#25292e",
    color: "white",
    fontSize: 16,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 16,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  modalButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
  },
  modalButtonText: {
    fontWeight: "700",
    fontSize: 15,
  },
  saveButton: {
    backgroundColor: "yellow",
  },
  saveButtonText: {
    color: "#25292e",
  },
  cancelButton: {
    backgroundColor: "#33383f",
  },
  cancelButtonText: {
    color: "white",
  },
  deleteButton: {
    padding: 6,
    marginLeft: 4,
  },
  toast: {
    position: "absolute",
    bottom: 100,
    left: 20,
    right: 20,
    backgroundColor: "#33383f",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    elevation: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  toastText: {
    color: "white",
    fontSize: 14,
  },
  toastUndo: {
    color: "yellow",
    fontWeight: "700",
    fontSize: 14,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  stubText: {
    color: "white",
    fontSize: 18,
    fontWeight: "700",
  },
  noteHeader: {
    paddingTop: 60,
    paddingBottom: 20,
    alignItems: "center",
  },
  noteNewButton: {
    position: "absolute",
    right: 20,
    top: 54,
    padding: 8,
  },
  noteListContent: {
    paddingHorizontal: 20,
    paddingBottom: 120,
  },
  noteCard: {
    backgroundColor: "#1e2126",
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  noteCardTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 4,
  },
  noteCardPreview: {
    color: "#8a8f98",
    fontSize: 13,
  },
  noteCardDate: {
    color: "#8a8f98",
    fontSize: 11,
    marginTop: 6,
  },
  noteEditorContainer: {
    flex: 1,
    paddingTop: 54,
    paddingHorizontal: 20,
    paddingBottom: 24,
  },
  noteEditorHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  noteEditorHeaderTitle: {
    color: "yellow",
    fontSize: 20,
    fontWeight: "800",
    flex: 1,
    marginHorizontal: 12,
    textAlign: "center",
  },
  noteEditorTitleInput: {
    color: "white",
    fontSize: 22,
    fontWeight: "800",
    padding: 0,
    marginBottom: 12,
  },
  noteEditorDivider: {
    borderBottomColor: "#33373d",
    borderBottomWidth: 1,
    marginBottom: 16,
  },
  noteEditorBodyInput: {
    color: "white",
    fontSize: 16,
    lineHeight: 24,
    padding: 0,
    flex: 1,
    textAlignVertical: "top",
  },
});

export const sizes = {
  icon: 24,
};
